### ISSUE TITLE
Issue with a button on the website

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/web-design-2-independent-project#2]
1) The contact button on the home page and work page is stretched, I believe it's because of the grid but I'm unable to fix it.
2) What is the best way to align forms and add spacing? Should it be grids?
@hellachella @mackenzierose

**Comment by MacKenzieRose** [comment]
1. You're totally right. The contact button colour is filling that whole grid chunk. The quickest way to get the sizing to revert to what you're used to would probably be to throw your `<a>` tag (for the button) inside of a `<div>` although I admit that's not an elegant solution.
2. Do you have any sketches for how you'd like it to look? Honestly, if your form is essentially one column, you probably don't need grids. But it depends what kind of functionality you're going for 🙂

**Comment by VanshitaGandhi** [comment]
Thanks @MacKenzieRose
