### ISSUE TITLE
Web Perfomance 

### ISSUE THREAD

**Issue by lilbaj** [VanshitaGandhi/web-design-2-independent-project#4]
<img width="1020" alt="Screen Shot 2020-12-11 at 1 32 09 PM" src="https://user-images.githubusercontent.com/55108804/101941142-93d10300-3bb5-11eb-9a91-7fe456ec9951.png">
<img width="1020" alt="Screen Shot 2020-12-11 at 1 32 19 PM" src="https://user-images.githubusercontent.com/55108804/101941151-959ac680-3bb5-11eb-8c22-c73ab546efd5.png">
Hey V, 
Great Job!! heres the test break down. i think this is pretty good!

**Comment by VanshitaGandhi** [comment]
Thank you @lilbaj
