### ISSUE TITLE
PC Opera

### ISSUE THREAD

**Issue by jessicali673** [VanshitaGandhi/web-design-2-independent-project#7]
Wow your website is absolutely gorgeous! Love your colour palette.
Everything looks great on PC Opera! 
The only thing is your footer is a little bit larger at the bottom
![image](https://user-images.githubusercontent.com/55094160/101944801-4e173900-3bbb-11eb-9b3b-a7f6a8d5afdb.png)

Besides that, everything is perfect!

**Comment by VanshitaGandhi** [comment]
Thank you @jessicali673
